AllCops:
  Exclude:
    - 'bin/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false


