matrix:
  include:
    - language: ruby
      cache: bundler
      rvm:
        - 2.4.1
      services:
        - mongodb
      before_install:
        - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
        - rvm @global do gem uninstall bundler -a -x -I || true
        - gem install bundler -v "< 2.0"
      script:
        - bundle exec rake
        - bundle exec rubocop
    - language: ruby
      cache: bundler
      rvm:
        - 2.3.8
      services:
        - mongodb
      before_install:
        - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
        - rvm @global do gem uninstall bundler -a -x -I || true
        - gem install bundler -v "< 2.0"
      script:
        - bundle exec rake
        - bundle exec rubocop
    - language: node_js
      install:
        - npm install -g codecov
        - npm install -g istanbul
      node_js:
        - "node"
        - "lts/*"
      cache:
        directories:
          - "node_modules"
      script:
        - yarn install
        - ./bin/build_cql_execution.sh
        - yarn run lint
        - yarn run test
        - ./bin/validate_dist.sh
        - codecov
