matrix:
  include:
    - language: ruby
      cache: bundler
      rvm:
        - 2.4.1
      services:
        - mongodb
      script:
        - bundle exec rake
        - bundle exec rubocop
    - language: ruby
      cache: bundler
      rvm:
        - 2.3.8
      services:
        - mongodb
      script:
        - bundle exec rake
        - bundle exec rubocop
    - language: node_js
      install:
        - npm install -g codecov
        - npm install -g istanbul
      node_js:
        - "node"
        - "lts/*"
      cache:
        directories:
          - "node_modules"
      script:
        - yarn install
        - yarn run lint
        - yarn run test
        - ./bin/validate_dist.sh
        - istanbul cover ./node_modules/jasmine/bin/jasmine.js
        - codecov
