matrix:
  include:
    - language: ruby
      cache: bundler
      rvm:
        - 2.4.1
      services:
        - mongodb
      script:
        - bundle exec rake
        - bundle exec rubocop
    - language: node_js
      node_js:
        - "node"
        - "lts/*"
      cache:
        directories:
          - "node_modules"
      script:
        - npm run lint
        - yarn run test
        - ./bin/validate_dist.sh
