module QDM
  # app/models/qdm/resource_container.rb
  class ResourceContainer < DataElement
    include Mongoid::Document
    embedded_in :patient
    field :Account
    field :ActivityDefinition
    field :AdverseEvent
    field :AllergyIntolerance
    field :Appointment
    field :AppointmentResponse
    field :AuditEvent
    field :Basic
    field :Binary
    field :BiologicallyDerivedProduct
    field :BodyStructure
    field :Bundle
    field :CapabilityStatement
    field :CarePlan
    field :CareTeam
    field :CatalogEntry
    field :ChargeItem
    field :ChargeItemDefinition
    field :Claim
    field :ClaimResponse
    field :ClinicalImpression
    field :QDM::CodeSystem
    field :Communication
    field :CommunicationRequest
    field :CompartmentDefinition
    field :Composition
    field :ConceptMap
    field :Condition
    field :Consent
    field :Contract
    field :Coverage
    field :CoverageEligibilityRequest
    field :CoverageEligibilityResponse
    field :DetectedIssue
    field :Device
    field :DeviceDefinition
    field :DeviceMetric
    field :DeviceRequest
    field :DeviceUseStatement
    field :DiagnosticReport
    field :DocumentManifest
    field :DocumentReference
    field :EffectEvidenceSynthesis
    field :Encounter
    field :Endpoint
    field :EnrollmentRequest
    field :EnrollmentResponse
    field :EpisodeOfCare
    field :EventDefinition
    field :Evidence
    field :EvidenceVariable
    field :ExampleScenario
    field :ExplanationOfBenefit
    field :FamilyMemberHistory
    field :Flag
    field :Goal
    field :GraphDefinition
    field :Group
    field :GuidanceResponse
    field :HealthcareService
    field :ImagingStudy
    field :Immunization
    field :ImmunizationEvaluation
    field :ImmunizationRecommendation
    field :ImplementationGuide
    field :InsurancePlan
    field :Invoice
    field :ItemInstance
    field :Library
    field :Linkage
    field :List
    field :Location
    field :Measure
    field :MeasureReport
    field :Media
    field :Medication
    field :MedicationAdministration
    field :MedicationDispense
    field :MedicationKnowledge
    field :MedicationRequest
    field :MedicationStatement
    field :MedicinalProduct
    field :MedicinalProductAuthorization
    field :MedicinalProductContraindication
    field :MedicinalProductIndication
    field :MedicinalProductIngredient
    field :MedicinalProductInteraction
    field :MedicinalProductManufactured
    field :MedicinalProductPackaged
    field :MedicinalProductPharmaceutical
    field :MedicinalProductUndesirableEffect
    field :MessageDefinition
    field :MessageHeader
    field :MolecularSequence
    field :NamingSystem
    field :NutritionOrder
    field :Observation
    field :ObservationDefinition
    field :OperationDefinition
    field :OperationOutcome
    field :Organization
    field :OrganizationAffiliation
    field :Patient
    field :PaymentNotice
    field :PaymentReconciliation
    field :Person
    field :PlanDefinition
    field :Practitioner
    field :PractitionerRole
    field :Procedure
    field :Provenance
    field :Questionnaire
    field :QuestionnaireResponse
    field :RelatedPerson
    field :RequestGroup
    field :ResearchDefinition
    field :ResearchElementDefinition
    field :ResearchStudy
    field :ResearchSubject
    field :RiskAssessment
    field :RiskEvidenceSynthesis
    field :Schedule
    field :SearchParameter
    field :ServiceRequest
    field :Slot
    field :Specimen
    field :SpecimenDefinition
    field :StructureDefinition
    field :StructureMap
    field :Subscription
    field :Substance
    field :SubstanceNucleicAcid
    field :SubstancePolymer
    field :SubstanceProtein
    field :SubstanceReferenceInformation
    field :SubstanceSourceMaterial
    field :SubstanceSpecification
    field :SupplyDelivery
    field :SupplyRequest
    field :Task
    field :TerminologyCapabilities
    field :TestReport
    field :TestScript
    field :ValueSet
    field :VerificationResult
    field :VisionPrescription
    field :Parameters
    field :qdmVersion, type: String, default: '4.0.0'
  end
end
