# Base QDM module (generated from lib/generate_models.rb) for QDM 5.3
module QDM
end
require 'mongoid'

# base types
require_relative 'qdm/basetypes/code'
require_relative 'qdm/basetypes/interval'
require_relative 'qdm/basetypes/quantity'
require_relative 'qdm/basetypes/data_element'

# Tacoma-specific models
require_relative 'qdm/tacoma/measure'
require_relative 'qdm/tacoma/measure_package'
require_relative 'qdm/tacoma/valueset'
require_relative 'qdm/tacoma/concept'

# Generated models
require_relative 'qdm/Patient'
require_relative 'qdm/Id'
require_relative 'qdm/Ratio'
require_relative 'qdm/PhysicalExamOrder'
require_relative 'qdm/Participation'
require_relative 'qdm/PatientCharacteristicSex'
require_relative 'qdm/CareGoal'
require_relative 'qdm/PatientCharacteristic'
require_relative 'qdm/PatientCharacteristicEthnicity'
require_relative 'qdm/PatientCharacteristicRace'
require_relative 'qdm/LaboratoryTestPerformed'
require_relative 'qdm/Symptom'
require_relative 'qdm/MedicationAdministered'
require_relative 'qdm/ProcedureRecommended'
require_relative 'qdm/EncounterPerformed'
require_relative 'qdm/Diagnosis'
require_relative 'qdm/CommunicationFromProviderToPatient'
require_relative 'qdm/AssessmentPerformed'
require_relative 'qdm/PatientCharacteristicClinicalTrialParticipant'
require_relative 'qdm/DeviceOrder'
require_relative 'qdm/DiagnosticStudyPerformed'
require_relative 'qdm/InterventionOrder'
require_relative 'qdm/FamilyHistory'
require_relative 'qdm/Component'
require_relative 'qdm/ResultComponent'
require_relative 'qdm/FacilityLocation'
require_relative 'qdm/CommunicationFromProviderToProvider'
require_relative 'qdm/MedicationActive'
require_relative 'qdm/LaboratoryTestOrder'
require_relative 'qdm/DiagnosticStudyOrder'
require_relative 'qdm/SubstanceOrder'
require_relative 'qdm/PatientCharacteristicPayer'
require_relative 'qdm/PatientCharacteristicExpired'
require_relative 'qdm/AssessmentRecommended'
require_relative 'qdm/ImmunizationAdministered'
require_relative 'qdm/SubstanceAdministered'
require_relative 'qdm/EncounterOrder'
require_relative 'qdm/EncounterRecommended'
require_relative 'qdm/ProcedurePerformed'
require_relative 'qdm/AllergyIntolerance'
require_relative 'qdm/ProviderCharacteristic'
require_relative 'qdm/PhysicalExamRecommended'
require_relative 'qdm/PatientCharacteristicBirthdate'
require_relative 'qdm/AdverseEvent'
require_relative 'qdm/CommunicationFromPatientToProvider'
require_relative 'qdm/DeviceRecommended'
require_relative 'qdm/DeviceApplied'
require_relative 'qdm/MedicationDischarge'
require_relative 'qdm/InterventionPerformed'
require_relative 'qdm/LaboratoryTestRecommended'
require_relative 'qdm/MedicationDispensed'
require_relative 'qdm/DiagnosticStudyRecommended'
require_relative 'qdm/ImmunizationOrder'
require_relative 'qdm/PatientCareExperience'
require_relative 'qdm/ProviderCareExperience'
require_relative 'qdm/ProcedureOrder'
require_relative 'qdm/MedicationOrder'
require_relative 'qdm/SubstanceRecommended'
require_relative 'qdm/InterventionRecommended'
require_relative 'qdm/PhysicalExamPerformed'
